apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-tnvhqexq 
  janus-idp.io/tekton: go-tnvhqexq
  backstage.io/kubernetes-id: go-tnvhqexq
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-tnvhqexq
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml